const Cocktail = require.main.require('./models/cocktail')

describe("Cocktail", () => {
  beforeEach( () => {
    this.subject =  new Cocktail()
  });
  describe("#all_json", () => {
    it("returns all cocktails", () => {
      const all_cocktails = this.subject.all_json()
      expect(all_cocktails).toEqual(
        [
          { name: "ABC" },
          { name: "AmarettoSour" },
          { name: "Americano" },
          { name: "Anaconda" },
          { name: "BacardiCocktail" },
          { name: "Barbarella" },
          { name: "BayBreeze" },
          { name: "Bellini" },
          { name: "BetweenTheSheets" },
          { name: "BlackRussian" },
          { name: "BlowJob" },
          { name: "Boulevardier" },
          { name: "Boyarskiy" },
          { name: "BraveBull" },
          { name: "Bronx" },
          { name: "BuckCocktails" },
          { name: "BucksFizz" },
          { name: "Bumbo" },
          { name: "Caipirinha" },
          { name: "Caipiroska" },
          { name: "CapeCod" },
          { name: "Chupacabra" },
          { name: "Cosmopolitain" },
          { name: "CubaLibre" },
          { name: "CultoALaVida" },
          { name: "DeltaSunset" },
          { name: "ElPresidente" },
          { name: "Fireball" },
          { name: "Flatliner" },
          { name: "FrenchConnection" },
          { name: "Garibaldi" },
          { name: "Gibson" },
          { name: "Gimlet" },
          { name: "GinAndSin" },
          { name: "GinRickey" },
          { name: "GinTonic" },
          { name: "Godfather" },
          { name: "Godmother" },
          { name: "Greyhound" },
          { name: "Highball" },
          { name: "HornyBull" },
          { name: "HotToddy" },
          { name: "IrishCarBomb" },
          { name: "JackAndCoke" },
          { name: "JellyBean" },
          { name: "Kamikaze" },
          { name: "Margarita" },
          { name: "MartiniDry" },
          { name: "MartiniLemonDrop" },
          { name: "MartiniPerfect" },
          { name: "MartiniSweet" },
          { name: "MartiniVodka" },
          { name: "MiamiBeach" },
          { name: "Mimosa" },
          { name: "MindEraser" },
          { name: "MintJulep" },
          { name: "Mojito" },
          { name: "MonkeyGland" },
          { name: "Mudslide" },
          { name: "Negroni" },
          { name: "RedSquare" },
          { name: "Rickey" },
          { name: "Rossini" },
          { name: "SaltyDog" },
          { name: "ScarlettOHara" },
          { name: "Screwdriver" },
          { name: "SeaBreeze" },
          { name: "Sidecar" },
          { name: "SilverBullet" },
          { name: "SlipperyNipple" },
          { name: "StrawberryDaiquiri" },
          { name: "StrawberryMargarita" },
          { name: "TequilaSlammer" },
          { name: "TequilaSunrise" },
          { name: "TootsieRoll" },
          { name: "Ward" },
          { name: "WhiteLady" },
        ]
      )
    })
  })
})
